<?php

use Illuminate\Database\Seeder;

class EmailsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('emails')->delete();
        
        \DB::table('emails')->insert(array (
            0 => 
            array (
                'id' => 1,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'vesper_general',
                'email' => 'sale201@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            1 => 
            array (
                'id' => 2,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'vesper_1p',
                'email' => 'sale201@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            2 => 
            array (
                'id' => 3,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'vesper_3p',
                'email' => 'sale201@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            3 => 
            array (
                'id' => 4,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'vchz',
                'email' => 'sale202@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            4 => 
            array (
                'id' => 5,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'kondensatory',
                'email' => 'sale202@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            5 => 
            array (
                'id' => 6,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'enip2',
                'email' => 'sale203@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            6 => 
            array (
                'id' => 7,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'enkm3',
                'email' => 'sale203@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            7 => 
            array (
                'id' => 8,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'enks2',
                'email' => 'sale203@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            8 => 
            array (
                'id' => 9,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'enks3m',
                'email' => 'sale203@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            9 => 
            array (
                'id' => 10,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'delta_c2000_vfd',
                'email' => 'sale204@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            10 => 
            array (
                'id' => 11,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'delta_cfp2000',
                'email' => 'sale204@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            11 => 
            array (
                'id' => 12,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'delta_ch2000',
                'email' => 'sale204@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            12 => 
            array (
                'id' => 13,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'delta_cp2000',
                'email' => 'sale204@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            13 => 
            array (
                'id' => 14,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'delta_ms300',
                'email' => 'sale204@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            14 => 
            array (
                'id' => 15,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'delta_vfde',
                'email' => 'sale204@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            15 => 
            array (
                'id' => 16,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'delta_vfdel',
                'email' => 'sale204@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            16 => 
            array (
                'id' => 17,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'delta_vfdl',
                'email' => 'sale204@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            17 => 
            array (
                'id' => 18,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'delta_vfdb',
                'email' => 'sale204@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            18 => 
            array (
                'id' => 19,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'moxa_eds208',
                'email' => 'sale205@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            19 => 
            array (
                'id' => 20,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'moxa_eds205',
                'email' => 'sale205@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            20 => 
            array (
                'id' => 21,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'moxa_eds210',
                'email' => 'sale205@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            21 => 
            array (
                'id' => 22,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'moxa_eds206',
                'email' => 'sale205@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            22 => 
            array (
                'id' => 23,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec_general',
                'email' => 'sale206@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            23 => 
            array (
                'id' => 24,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec132_russia',
                'email' => 'sale206@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            24 => 
            array (
                'id' => 25,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec133_russia',
                'email' => 'sale206@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            25 => 
            array (
                'id' => 26,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130e_russia',
                'email' => 'sale206@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            26 => 
            array (
                'id' => 27,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130eh_russia',
                'email' => 'sale206@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            27 => 
            array (
                'id' => 28,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130p_russia',
                'email' => 'sale206@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            28 => 
            array (
                'id' => 29,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec135_russia',
                'email' => 'sale206@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            29 => 
            array (
                'id' => 30,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec172_russia',
                'email' => 'sale206@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            30 => 
            array (
                'id' => 31,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec175_russia',
                'email' => 'sale206@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            31 => 
            array (
                'id' => 32,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec_general_armenia',
                'email' => 'sale207@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            32 => 
            array (
                'id' => 33,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec132_armenia',
                'email' => 'sale207@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            33 => 
            array (
                'id' => 34,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec133_armenia',
                'email' => 'sale207@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            34 => 
            array (
                'id' => 35,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130e_armenia',
                'email' => 'sale207@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            35 => 
            array (
                'id' => 36,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130eh_armenia',
                'email' => 'sale207@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            36 => 
            array (
                'id' => 37,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130p_armenia',
                'email' => 'sale207@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            37 => 
            array (
                'id' => 38,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec135_armenia',
                'email' => 'sale207@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            38 => 
            array (
                'id' => 39,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec172_armenia',
                'email' => 'sale207@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            39 => 
            array (
                'id' => 40,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec175_armenia',
                'email' => 'sale207@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            40 => 
            array (
                'id' => 41,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec_general_belarus',
                'email' => 'sale208@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            41 => 
            array (
                'id' => 42,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec132_belarus',
                'email' => 'sale208@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            42 => 
            array (
                'id' => 43,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec133_belarus',
                'email' => 'sale208@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            43 => 
            array (
                'id' => 44,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130e_belarus',
                'email' => 'sale208@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            44 => 
            array (
                'id' => 45,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130e_belarus',
                'email' => 'sale208@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            45 => 
            array (
                'id' => 46,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130eh_belarus',
                'email' => 'sale208@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            46 => 
            array (
                'id' => 47,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130p_belarus',
                'email' => 'sale208@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            47 => 
            array (
                'id' => 48,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec135_belarus',
                'email' => 'sale208@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            48 => 
            array (
                'id' => 49,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec172_belarus',
                'email' => 'sale208@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            49 => 
            array (
                'id' => 50,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec175_belarus',
                'email' => 'sale208@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            50 => 
            array (
                'id' => 51,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec_general_kazakh',
                'email' => 'sale209@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            51 => 
            array (
                'id' => 52,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec132_kazakh',
                'email' => 'sale209@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            52 => 
            array (
                'id' => 53,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec133_kazakh',
                'email' => 'sale209@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            53 => 
            array (
                'id' => 54,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130e_kazakh',
                'email' => 'sale209@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            54 => 
            array (
                'id' => 55,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130eh_kazakh',
                'email' => 'sale209@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            55 => 
            array (
                'id' => 56,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130p_kazakh',
                'email' => 'sale209@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            56 => 
            array (
                'id' => 57,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec135_kazakh',
                'email' => 'sale209@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            57 => 
            array (
                'id' => 58,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec172_kazakh',
                'email' => 'sale209@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            58 => 
            array (
                'id' => 59,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec175_kazakh',
                'email' => 'sale209@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            59 => 
            array (
                'id' => 60,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec_general_kyrgyz',
                'email' => 'sale210@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            60 => 
            array (
                'id' => 61,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec132_kyrgyz',
                'email' => 'sale210@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            61 => 
            array (
                'id' => 62,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec133_kyrgyz',
                'email' => 'sale210@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            62 => 
            array (
                'id' => 63,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130e_kyrgyz',
                'email' => 'sale210@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            63 => 
            array (
                'id' => 64,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130eh_kyrgyz',
                'email' => 'sale210@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            64 => 
            array (
                'id' => 65,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec130p_kyrgyz',
                'email' => 'sale210@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            65 => 
            array (
                'id' => 66,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec135_kyrgyz',
                'email' => 'sale210@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            66 => 
            array (
                'id' => 67,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec172_kyrgyz',
                'email' => 'sale210@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            67 => 
            array (
                'id' => 68,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => 'satec175_kyrgyz',
                'email' => 'sale210@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            68 => 
            array (
                'id' => 69,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'satec_pm130eh',
                'email' => 'sale101@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            69 => 
            array (
                'id' => 70,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'satec_pm130p',
                'email' => 'sale101@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            70 => 
            array (
                'id' => 71,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'satec_em132',
                'email' => 'sale101@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            71 => 
            array (
                'id' => 72,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'satec_pm175',
                'email' => 'sale101@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            72 => 
            array (
                'id' => 73,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'satec_pm130e',
                'email' => 'sale101@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            73 => 
            array (
                'id' => 74,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'satec_em133',
                'email' => 'sale101@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            74 => 
            array (
                'id' => 75,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'satec_pm180',
                'email' => 'sale101@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            75 => 
            array (
                'id' => 76,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'satec_pm172',
                'email' => 'sale101@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            76 => 
            array (
                'id' => 77,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'satec_general',
                'email' => 'sale101@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            77 => 
            array (
                'id' => 78,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'bfmii',
                'email' => 'sale101@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            78 => 
            array (
                'id' => 79,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'enmi3',
                'email' => 'sale102@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            79 => 
            array (
                'id' => 80,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'enmi4',
                'email' => 'sale102@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            80 => 
            array (
                'id' => 81,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'enmv',
                'email' => 'sale102@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            81 => 
            array (
                'id' => 82,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'enmi5',
                'email' => 'sale102@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            82 => 
            array (
                'id' => 83,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'enip2',
                'email' => 'sale102@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            83 => 
            array (
                'id' => 84,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'enkm3',
                'email' => 'sale102@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            84 => 
            array (
                'id' => 85,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'enks3m',
                'email' => 'sale102@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            85 => 
            array (
                'id' => 86,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'enks2',
                'email' => 'sale102@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            86 => 
            array (
                'id' => 87,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'enmi7',
                'email' => 'sale102@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            87 => 
            array (
                'id' => 88,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'esm',
                'email' => 'sale102@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            88 => 
            array (
                'id' => 89,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'plc63_owen',
                'email' => 'sale103@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            89 => 
            array (
                'id' => 90,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'owen_general',
                'email' => 'sale103@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            90 => 
            array (
                'id' => 91,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'pchv1',
                'email' => 'sale103@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            91 => 
            array (
                'id' => 92,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'upp',
                'email' => 'sale103@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            92 => 
            array (
                'id' => 93,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'pchv2',
                'email' => 'sale103@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            93 => 
            array (
                'id' => 94,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'plc73_owen',
                'email' => 'sale103@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            94 => 
            array (
                'id' => 95,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'plc_owen',
                'email' => 'sale103@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            95 => 
            array (
                'id' => 96,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'pchv3',
                'email' => 'sale103@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            96 => 
            array (
                'id' => 97,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vesper_general',
                'email' => 'sale104@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            97 => 
            array (
                'id' => 98,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vesper_9011',
                'email' => 'sale104@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            98 => 
            array (
                'id' => 99,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vesper_7011',
                'email' => 'sale104@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            99 => 
            array (
                'id' => 100,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vesper_7012',
                'email' => 'sale104@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            100 => 
            array (
                'id' => 101,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vesper_9100',
                'email' => 'sale104@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            101 => 
            array (
                'id' => 102,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vesper_8200',
                'email' => 'sale104@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            102 => 
            array (
                'id' => 103,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vesper_8400',
                'email' => 'sale104@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            103 => 
            array (
                'id' => 104,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vesper_7500',
                'email' => 'sale104@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            104 => 
            array (
                'id' => 105,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vesper_e2_mini',
                'email' => 'sale104@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            105 => 
            array (
                'id' => 106,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vesper_p8402',
                'email' => 'sale104@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            106 => 
            array (
                'id' => 107,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vz630_uznteh',
                'email' => 'sale105@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            107 => 
            array (
                'id' => 108,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vz1250_uznteh',
                'email' => 'sale105@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            108 => 
            array (
                'id' => 109,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'vz_uznteh',
                'email' => 'sale105@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            109 => 
            array (
                'id' => 110,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'coupling_capacitors',
                'email' => 'sale105@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            110 => 
            array (
                'id' => 111,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'coupling_capacitors_sm',
                'email' => 'sale105@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            111 => 
            array (
                'id' => 112,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'coupling_capacitors_ksa',
                'email' => 'sale105@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            112 => 
            array (
                'id' => 113,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'binom3',
                'email' => 'sale106@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            113 => 
            array (
                'id' => 114,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'binom334',
                'email' => 'sale106@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            114 => 
            array (
                'id' => 115,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'binom339',
                'email' => 'sale106@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            115 => 
            array (
                'id' => 116,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'delta_general',
                'email' => 'sale107@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            116 => 
            array (
                'id' => 117,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'delta_vfd',
                'email' => 'sale107@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            117 => 
            array (
                'id' => 118,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'moxa_eds205',
                'email' => 'sale108@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            118 => 
            array (
                'id' => 119,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'moxa_switches',
                'email' => 'sale108@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            119 => 
            array (
                'id' => 120,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'nport5100',
                'email' => 'sale108@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            120 => 
            array (
                'id' => 121,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'nport_general',
                'email' => 'sale108@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            121 => 
            array (
                'id' => 123,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'uport',
                'email' => 'sale108@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            122 => 
            array (
                'id' => 124,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'uport1150',
                'email' => 'sale108@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            123 => 
            array (
                'id' => 125,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'moxa_general',
                'email' => 'sale108@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            124 => 
            array (
                'id' => 126,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'moxa_converter',
                'email' => 'sale108@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            125 => 
            array (
                'id' => 127,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'mgate',
                'email' => 'sale108@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            126 => 
            array (
                'id' => 128,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'skat_akb_lifepo4',
                'email' => 'sale109@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            127 => 
            array (
                'id' => 129,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => 'skat_ups_lifepo4',
                'email' => 'sale109@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            128 => 
            array (
                'id' => 130,
                'source' => 'yandex',
                'medium' => 'cpc',
                'campaign' => NULL,
                'email' => 'sale115@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            129 => 
            array (
                'id' => 131,
                'source' => 'google',
                'medium' => 'cpc',
                'campaign' => NULL,
                'email' => 'sale215@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
            130 => 
            array (
                'id' => 132,
                'source' => 'Sandsay',
                'medium' => 'email',
                'campaign' => NULL,
                'email' => 'sale1@uralenergotel.ru',
                'term' => NULL,
                'content' => NULL,
                'type' => NULL,
                'created_at' => '2019-09-19 00:00:00',
                'updated_at' => '2019-09-19 00:00:00',
            ),
        ));
        
        
    }
}