<?php

use Illuminate\Database\Seeder;

class LockerImagesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('locker_images')->delete();
        
        \DB::table('locker_images')->insert(array (
            0 => 
            array (
                'id' => 15,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/energoservice.png',
                'alt_name' => 'Энергосервис',
                'url' => 'https://uralenergotel.ru/brand/energoservis/',
                'created_at' => '2019-02-08 15:35:09',
                'updated_at' => '2019-02-08 15:35:09',
            ),
            1 => 
            array (
                'id' => 16,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/prosoft.png',
                'alt_name' => 'ProSoft',
                'url' => NULL,
                'created_at' => '2019-02-08 15:38:10',
                'updated_at' => '2019-02-08 15:40:32',
            ),
            2 => 
            array (
                'id' => 17,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/electropribor.png',
                'alt_name' => 'Электроприбор',
                'url' => 'https://uralenergotel.ru/brand/electropribor/',
                'created_at' => '2019-02-08 15:38:19',
                'updated_at' => '2019-02-08 15:40:55',
            ),
            3 => 
            array (
                'id' => 19,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/nnpo-frunze.png',
                'alt_name' => 'ННПО Завод им. Фрунзе',
                'url' => 'https://uralenergotel.ru/brand/nnpo-frunze/',
                'created_at' => '2019-02-08 15:38:58',
                'updated_at' => '2019-02-08 15:41:42',
            ),
            4 => 
            array (
                'id' => 20,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/satec.png',
                'alt_name' => 'Satec',
                'url' => 'https://uralenergotel.ru/brand/satec_plc_as/',
                'created_at' => '2019-02-08 15:39:10',
                'updated_at' => '2019-02-08 15:41:49',
            ),
            5 => 
            array (
                'id' => 21,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/ntkpriborenergo.png',
                'alt_name' => 'НТК Приборэнерго',
                'url' => 'https://uralenergotel.ru/brand/ntk-priborenergo/',
                'created_at' => '2019-02-08 15:39:19',
                'updated_at' => '2019-02-08 15:42:16',
            ),
            6 => 
            array (
                'id' => 22,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/odo_energopribor.png',
                'alt_name' => 'ОДО Энергоприбор',
                'url' => 'https://uralenergotel.ru/brand/odo-energopribor/',
                'created_at' => '2019-02-08 15:39:34',
                'updated_at' => '2019-02-08 15:44:41',
            ),
            7 => 
            array (
                'id' => 23,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/directlogic.png',
                'alt_name' => 'Direct Logic',
                'url' => NULL,
                'created_at' => '2019-02-08 15:39:42',
                'updated_at' => '2019-02-08 15:44:57',
            ),
            8 => 
            array (
                'id' => 24,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/owen.png',
                'alt_name' => 'Овен',
                'url' => 'https://uralenergotel.ru/brand/owen/',
                'created_at' => '2019-02-08 15:39:53',
                'updated_at' => '2019-02-08 15:39:53',
            ),
            9 => 
            array (
                'id' => 25,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/npf_proryv.png',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-08 15:40:08',
                'updated_at' => '2019-02-08 15:40:08',
            ),
            10 => 
            array (
                'id' => 26,
                'locker_id' => 1,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/ks.png',
                'alt_name' => 'К-С',
                'url' => 'https://uralenergotel.ru/brand/k-s/',
                'created_at' => '2019-02-08 15:41:27',
                'updated_at' => '2019-02-08 15:59:51',
            ),
            11 => 
            array (
                'id' => 27,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/abb.png',
                'alt_name' => 'ABB',
                'url' => NULL,
                'created_at' => '2019-02-11 08:59:53',
                'updated_at' => '2019-02-11 09:02:44',
            ),
            12 => 
            array (
                'id' => 29,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/agat-rt.png',
                'alt_name' => 'Агат РТ',
                'url' => NULL,
                'created_at' => '2019-02-11 09:00:22',
                'updated_at' => '2019-02-11 09:02:48',
            ),
            13 => 
            array (
                'id' => 30,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/alcatel.png',
                'alt_name' => 'Alcatel',
                'url' => NULL,
                'created_at' => '2019-02-11 09:00:30',
                'updated_at' => '2019-02-11 09:02:51',
            ),
            14 => 
            array (
                'id' => 31,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/avaya.png',
                'alt_name' => 'Avaya',
                'url' => NULL,
                'created_at' => '2019-02-11 09:00:38',
                'updated_at' => '2019-02-11 09:02:54',
            ),
            15 => 
            array (
                'id' => 32,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/ciena.png',
                'alt_name' => 'Ciena',
                'url' => NULL,
                'created_at' => '2019-02-11 09:00:44',
                'updated_at' => '2019-02-11 09:02:56',
            ),
            16 => 
            array (
                'id' => 34,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/eltex.png',
                'alt_name' => 'Eltex',
                'url' => NULL,
                'created_at' => '2019-02-11 09:01:05',
                'updated_at' => '2019-02-11 09:02:59',
            ),
            17 => 
            array (
                'id' => 35,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/huawei.png',
                'alt_name' => 'Huawei',
                'url' => NULL,
                'created_at' => '2019-02-11 09:01:15',
                'updated_at' => '2019-02-11 09:03:02',
            ),
            18 => 
            array (
                'id' => 36,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/inter_m.png',
                'alt_name' => 'inter M',
                'url' => NULL,
                'created_at' => '2019-02-11 09:01:25',
                'updated_at' => '2019-02-11 09:03:06',
            ),
            19 => 
            array (
                'id' => 37,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/irz.png',
                'alt_name' => 'IRZ',
                'url' => 'https://uralenergotel.ru/brand/irz/',
                'created_at' => '2019-02-11 09:01:35',
                'updated_at' => '2019-02-11 09:01:35',
            ),
            20 => 
            array (
                'id' => 38,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/lenovo.png',
                'alt_name' => 'Lenovo',
                'url' => NULL,
                'created_at' => '2019-02-11 09:01:46',
                'updated_at' => '2019-02-11 09:03:14',
            ),
            21 => 
            array (
                'id' => 39,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/marconi.png',
                'alt_name' => 'Marconi',
                'url' => NULL,
                'created_at' => '2019-02-11 09:02:04',
                'updated_at' => '2019-02-11 09:03:18',
            ),
            22 => 
            array (
                'id' => 40,
                'locker_id' => 2,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/moxa.png',
                'alt_name' => 'Moxa',
                'url' => NULL,
                'created_at' => '2019-02-11 09:02:13',
                'updated_at' => '2019-02-11 09:03:22',
            ),
            23 => 
            array (
                'id' => 41,
                'locker_id' => 5,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/rittal.png',
                'alt_name' => 'Rittal',
                'url' => NULL,
                'created_at' => '2019-02-11 09:26:33',
                'updated_at' => '2019-02-11 09:27:44',
            ),
            24 => 
            array (
                'id' => 42,
                'locker_id' => 5,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/dkc.png',
                'alt_name' => 'DKC',
                'url' => NULL,
                'created_at' => '2019-02-11 09:26:41',
                'updated_at' => '2019-02-11 09:27:46',
            ),
            25 => 
            array (
                'id' => 43,
                'locker_id' => 5,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/cmo.png',
                'alt_name' => 'ЦМО',
                'url' => NULL,
                'created_at' => '2019-02-11 09:26:48',
                'updated_at' => '2019-02-11 09:27:49',
            ),
            26 => 
            array (
                'id' => 44,
                'locker_id' => 5,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/abb.png',
                'alt_name' => 'ABB',
                'url' => NULL,
                'created_at' => '2019-02-11 09:26:52',
                'updated_at' => '2019-02-11 09:27:52',
            ),
            27 => 
            array (
                'id' => 45,
                'locker_id' => 5,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/schneider.png',
                'alt_name' => 'Schneider Electric',
                'url' => NULL,
                'created_at' => '2019-02-11 09:27:04',
                'updated_at' => '2019-02-11 09:27:58',
            ),
            28 => 
            array (
                'id' => 46,
                'locker_id' => 5,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/phoenixcontact.png',
                'alt_name' => 'Phoenix Contact',
                'url' => NULL,
                'created_at' => '2019-02-11 09:27:14',
                'updated_at' => '2019-02-11 09:28:03',
            ),
            29 => 
            array (
                'id' => 47,
                'locker_id' => 5,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/keaz.png',
                'alt_name' => 'КЭАЗ',
                'url' => NULL,
                'created_at' => '2019-02-11 09:27:27',
                'updated_at' => '2019-02-11 09:28:06',
            ),
            30 => 
            array (
                'id' => 48,
                'locker_id' => 5,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/klemsan.png',
                'alt_name' => 'Klemsan',
                'url' => NULL,
                'created_at' => '2019-02-11 09:27:38',
                'updated_at' => '2019-02-11 09:28:10',
            ),
            31 => 
            array (
                'id' => 49,
                'locker_id' => 4,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/nsgate.png',
                'alt_name' => 'NSGate',
                'url' => NULL,
                'created_at' => '2019-02-11 15:31:31',
                'updated_at' => '2019-02-11 16:06:49',
            ),
            32 => 
            array (
                'id' => 50,
                'locker_id' => 4,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/dkc.png',
                'alt_name' => 'DKC',
                'url' => NULL,
                'created_at' => '2019-02-11 15:31:40',
                'updated_at' => '2019-02-11 16:06:48',
            ),
            33 => 
            array (
                'id' => 51,
                'locker_id' => 4,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/moxa.png',
                'alt_name' => 'Moxa',
                'url' => NULL,
                'created_at' => '2019-02-11 15:53:20',
                'updated_at' => '2019-02-11 16:06:48',
            ),
            34 => 
            array (
                'id' => 52,
                'locker_id' => 4,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/axis.png',
                'alt_name' => 'Axis',
                'url' => NULL,
                'created_at' => '2019-02-11 16:06:20',
                'updated_at' => '2019-02-11 16:06:48',
            ),
            35 => 
            array (
                'id' => 53,
                'locker_id' => 4,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/uralenergotel.png',
                'alt_name' => 'Уралэнерготел',
                'url' => NULL,
                'created_at' => '2019-02-11 16:06:28',
                'updated_at' => '2019-02-11 16:06:47',
            ),
            36 => 
            array (
                'id' => 54,
                'locker_id' => 4,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/beward.png',
                'alt_name' => 'Beward',
                'url' => NULL,
                'created_at' => '2019-02-11 16:50:39',
                'updated_at' => '2019-02-11 16:51:02',
            ),
            37 => 
            array (
                'id' => 55,
                'locker_id' => 4,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/evidence.png',
                'alt_name' => 'Evidence',
                'url' => NULL,
                'created_at' => '2019-02-11 16:50:57',
                'updated_at' => '2019-02-11 16:51:08',
            ),
            38 => 
            array (
                'id' => 56,
                'locker_id' => 3,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/abb.png',
                'alt_name' => 'ABB',
                'url' => NULL,
                'created_at' => '2019-02-14 09:01:49',
                'updated_at' => '2019-02-14 09:03:33',
            ),
            39 => 
            array (
                'id' => 57,
                'locker_id' => 3,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/eaton.png',
                'alt_name' => 'Eaton',
                'url' => NULL,
                'created_at' => '2019-02-14 09:01:58',
                'updated_at' => '2019-02-14 09:03:37',
            ),
            40 => 
            array (
                'id' => 58,
                'locker_id' => 3,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/eltek.png',
                'alt_name' => 'Eltek',
                'url' => NULL,
                'created_at' => '2019-02-14 09:02:08',
                'updated_at' => '2019-02-14 09:03:40',
            ),
            41 => 
            array (
                'id' => 59,
                'locker_id' => 3,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/apc.png',
                'alt_name' => 'APC',
                'url' => NULL,
                'created_at' => '2019-02-14 09:02:15',
                'updated_at' => '2019-02-14 09:03:42',
            ),
            42 => 
            array (
                'id' => 60,
                'locker_id' => 3,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/stil.png',
                'alt_name' => 'Штиль',
                'url' => NULL,
                'created_at' => '2019-02-14 09:02:32',
                'updated_at' => '2019-02-14 09:03:45',
            ),
            43 => 
            array (
                'id' => 61,
                'locker_id' => 3,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/vorpost.png',
                'alt_name' => 'Форпост',
                'url' => NULL,
                'created_at' => '2019-02-14 09:02:42',
                'updated_at' => '2019-02-14 09:03:49',
            ),
            44 => 
            array (
                'id' => 62,
                'locker_id' => 3,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/socomec.png',
                'alt_name' => 'Socomec',
                'url' => NULL,
                'created_at' => '2019-02-14 09:02:51',
                'updated_at' => '2019-02-14 09:03:56',
            ),
            45 => 
            array (
                'id' => 63,
                'locker_id' => 3,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/finder.png',
                'alt_name' => 'Finder',
                'url' => NULL,
                'created_at' => '2019-02-14 09:02:59',
                'updated_at' => '2019-02-14 09:03:59',
            ),
            46 => 
            array (
                'id' => 64,
                'locker_id' => 3,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/schneider.png',
                'alt_name' => 'Schneider Electric',
                'url' => NULL,
                'created_at' => '2019-02-14 09:03:16',
                'updated_at' => '2019-02-14 09:04:05',
            ),
            47 => 
            array (
                'id' => 65,
                'locker_id' => 3,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/keaz.png',
                'alt_name' => 'КЭАЗ',
                'url' => NULL,
                'created_at' => '2019-02-14 09:03:27',
                'updated_at' => '2019-02-14 09:03:53',
            ),
            48 => 
            array (
                'id' => 66,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm1_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:56:48',
                'updated_at' => '2019-02-14 14:56:48',
            ),
            49 => 
            array (
                'id' => 67,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm2_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:57:00',
                'updated_at' => '2019-02-14 14:57:00',
            ),
            50 => 
            array (
                'id' => 68,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm3_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:57:11',
                'updated_at' => '2019-02-14 14:57:11',
            ),
            51 => 
            array (
                'id' => 69,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm4_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:57:21',
                'updated_at' => '2019-02-14 14:57:21',
            ),
            52 => 
            array (
                'id' => 70,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm5_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:57:37',
                'updated_at' => '2019-02-14 14:57:37',
            ),
            53 => 
            array (
                'id' => 71,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm6_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:57:49',
                'updated_at' => '2019-02-14 14:57:49',
            ),
            54 => 
            array (
                'id' => 72,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm7_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:57:59',
                'updated_at' => '2019-02-14 14:57:59',
            ),
            55 => 
            array (
                'id' => 73,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm8_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:58:08',
                'updated_at' => '2019-02-14 14:58:08',
            ),
            56 => 
            array (
                'id' => 74,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm9_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:58:18',
                'updated_at' => '2019-02-14 14:58:18',
            ),
            57 => 
            array (
                'id' => 75,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm10_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:58:27',
                'updated_at' => '2019-02-14 14:58:27',
            ),
            58 => 
            array (
                'id' => 76,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm11_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:58:49',
                'updated_at' => '2019-02-14 14:58:49',
            ),
            59 => 
            array (
                'id' => 77,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm12_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:58:57',
                'updated_at' => '2019-02-14 14:58:57',
            ),
            60 => 
            array (
                'id' => 78,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm13_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:59:23',
                'updated_at' => '2019-02-14 14:59:23',
            ),
            61 => 
            array (
                'id' => 79,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm14_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:59:31',
                'updated_at' => '2019-02-14 14:59:31',
            ),
            62 => 
            array (
                'id' => 80,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm15_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 14:59:51',
                'updated_at' => '2019-02-14 14:59:51',
            ),
            63 => 
            array (
                'id' => 81,
                'locker_id' => 1,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/tm_and_askue/carousel_tm16_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:00:09',
                'updated_at' => '2019-02-14 15:00:09',
            ),
            64 => 
            array (
                'id' => 82,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz01n_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-03-13 11:38:18',
                'updated_at' => '2019-03-13 11:38:18',
            ),
            65 => 
            array (
                'id' => 83,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz02_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:22:39',
                'updated_at' => '2019-02-14 15:22:39',
            ),
            66 => 
            array (
                'id' => 84,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz03_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:22:48',
                'updated_at' => '2019-02-14 15:22:48',
            ),
            67 => 
            array (
                'id' => 85,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz04_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:22:57',
                'updated_at' => '2019-02-14 15:22:57',
            ),
            68 => 
            array (
                'id' => 86,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz05_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:23:06',
                'updated_at' => '2019-02-14 15:23:06',
            ),
            69 => 
            array (
                'id' => 87,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz06_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:23:27',
                'updated_at' => '2019-02-14 15:23:27',
            ),
            70 => 
            array (
                'id' => 88,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz07_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:24:13',
                'updated_at' => '2019-02-14 15:24:13',
            ),
            71 => 
            array (
                'id' => 89,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz08_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:24:25',
                'updated_at' => '2019-02-14 15:24:25',
            ),
            72 => 
            array (
                'id' => 90,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz09_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:25:20',
                'updated_at' => '2019-02-14 15:25:20',
            ),
            73 => 
            array (
                'id' => 91,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz10_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:25:47',
                'updated_at' => '2019-02-14 15:25:47',
            ),
            74 => 
            array (
                'id' => 92,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz11_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:25:59',
                'updated_at' => '2019-02-14 15:25:59',
            ),
            75 => 
            array (
                'id' => 93,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz01_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:22:29',
                'updated_at' => '2019-02-14 15:22:29',
            ),
            76 => 
            array (
                'id' => 94,
                'locker_id' => 3,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/ibp/carousel_ibp01_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:29:49',
                'updated_at' => '2019-02-14 15:29:49',
            ),
            77 => 
            array (
                'id' => 95,
                'locker_id' => 3,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/ibp/carousel_ibp02_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:29:58',
                'updated_at' => '2019-02-14 15:29:58',
            ),
            78 => 
            array (
                'id' => 96,
                'locker_id' => 3,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/ibp/carousel_ibp03_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:30:21',
                'updated_at' => '2019-02-14 15:30:21',
            ),
            79 => 
            array (
                'id' => 97,
                'locker_id' => 3,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/ibp/carousel_ibp04_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:30:51',
                'updated_at' => '2019-02-14 15:30:51',
            ),
            80 => 
            array (
                'id' => 98,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku01n_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-03-13 11:38:40',
                'updated_at' => '2019-03-13 11:38:40',
            ),
            81 => 
            array (
                'id' => 99,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku02_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:32:49',
                'updated_at' => '2019-02-14 15:32:49',
            ),
            82 => 
            array (
                'id' => 101,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku04_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:33:18',
                'updated_at' => '2019-02-14 15:33:18',
            ),
            83 => 
            array (
                'id' => 102,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku05_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:33:34',
                'updated_at' => '2019-02-14 15:33:34',
            ),
            84 => 
            array (
                'id' => 103,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku06_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:34:00',
                'updated_at' => '2019-02-14 15:34:00',
            ),
            85 => 
            array (
                'id' => 104,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku07_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:34:07',
                'updated_at' => '2019-02-14 15:34:07',
            ),
            86 => 
            array (
                'id' => 105,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku08_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:34:19',
                'updated_at' => '2019-02-14 15:34:19',
            ),
            87 => 
            array (
                'id' => 106,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku09_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:34:34',
                'updated_at' => '2019-02-14 15:34:34',
            ),
            88 => 
            array (
                'id' => 107,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku10_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:34:54',
                'updated_at' => '2019-02-14 15:34:54',
            ),
            89 => 
            array (
                'id' => 108,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku11_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:35:09',
                'updated_at' => '2019-02-14 15:35:09',
            ),
            90 => 
            array (
                'id' => 109,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku12_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:35:21',
                'updated_at' => '2019-02-14 15:35:21',
            ),
            91 => 
            array (
                'id' => 110,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku13_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:36:09',
                'updated_at' => '2019-02-14 15:36:09',
            ),
            92 => 
            array (
                'id' => 111,
                'locker_id' => 4,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/surveillance/carousel_vn01_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:37:33',
                'updated_at' => '2019-02-14 15:37:33',
            ),
            93 => 
            array (
                'id' => 112,
                'locker_id' => 4,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/surveillance/carousel_vn02_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:37:43',
                'updated_at' => '2019-02-14 15:37:43',
            ),
            94 => 
            array (
                'id' => 113,
                'locker_id' => 4,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/surveillance/carousel_vn03_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:37:53',
                'updated_at' => '2019-02-14 15:37:53',
            ),
            95 => 
            array (
                'id' => 114,
                'locker_id' => 4,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/surveillance/carousel_vn04_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:38:12',
                'updated_at' => '2019-02-14 15:38:12',
            ),
            96 => 
            array (
                'id' => 115,
                'locker_id' => 4,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/surveillance/carousel_vn05_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:38:25',
                'updated_at' => '2019-02-14 15:38:25',
            ),
            97 => 
            array (
                'id' => 116,
                'locker_id' => 4,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/surveillance/carousel_vn06_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:38:33',
                'updated_at' => '2019-02-14 15:38:33',
            ),
            98 => 
            array (
                'id' => 117,
                'locker_id' => 6,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/substation/1 compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-03-05 17:38:01',
                'updated_at' => '2019-03-05 17:38:01',
            ),
            99 => 
            array (
                'id' => 118,
                'locker_id' => 6,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/substation/2 compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-03-05 17:38:13',
                'updated_at' => '2019-03-05 17:38:13',
            ),
            100 => 
            array (
                'id' => 124,
                'locker_id' => 6,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/substation/panels1.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-03-05 17:44:42',
                'updated_at' => '2019-03-05 17:44:42',
            ),
            101 => 
            array (
                'id' => 126,
                'locker_id' => 6,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/energoservice.png',
                'alt_name' => 'Энергосервис',
                'url' => 'https://uralenergotel.ru/brand/energoservis/',
                'created_at' => '2019-03-05 17:45:09',
                'updated_at' => '2019-03-05 17:45:09',
            ),
            102 => 
            array (
                'id' => 127,
                'locker_id' => 6,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/electropribor.png',
                'alt_name' => 'Электроприбор',
                'url' => 'https://uralenergotel.ru/brand/electropribor/',
                'created_at' => '2019-03-05 17:45:29',
                'updated_at' => '2019-03-05 18:16:53',
            ),
            103 => 
            array (
                'id' => 128,
                'locker_id' => 6,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/КС.png',
                'alt_name' => 'КС-Трейдинг',
                'url' => 'https://uralenergotel.ru/brand/k-s/',
                'created_at' => '2019-03-05 17:45:50',
                'updated_at' => '2019-03-05 18:16:58',
            ),
            104 => 
            array (
                'id' => 129,
                'locker_id' => 6,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/schneider.png',
                'alt_name' => 'Schneider Electric',
                'url' => NULL,
                'created_at' => '2019-03-05 17:46:44',
                'updated_at' => '2019-03-05 18:17:05',
            ),
            105 => 
            array (
                'id' => 130,
                'locker_id' => 6,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/uralenergotel.png',
                'alt_name' => 'Уралэнерготел',
                'url' => 'https://uralenergotel.ru/brand/uralenergotel/',
                'created_at' => '2019-03-05 18:14:56',
                'updated_at' => '2019-03-05 18:17:09',
            ),
            106 => 
            array (
                'id' => 131,
                'locker_id' => 6,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/elkey.png',
                'alt_name' => 'Elkey',
                'url' => NULL,
                'created_at' => '2019-03-05 18:15:07',
                'updated_at' => '2019-03-05 18:17:13',
            ),
            107 => 
            array (
                'id' => 132,
                'locker_id' => 6,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/eti.png',
                'alt_name' => 'Eti',
                'url' => NULL,
                'created_at' => '2019-03-05 18:15:23',
                'updated_at' => '2019-03-05 18:17:19',
            ),
            108 => 
            array (
                'id' => 133,
                'locker_id' => 6,
                'type' => 2,
                'image_path' => '/storage/uploads/brands/shkafy-individualnoi-sborki/kaskad-electro.png',
                'alt_name' => 'Kaskad Electro',
                'url' => NULL,
                'created_at' => '2019-03-05 18:15:34',
                'updated_at' => '2019-03-05 18:17:25',
            ),
            109 => 
            array (
                'id' => 136,
                'locker_id' => 6,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/substation/03.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-03-05 18:50:50',
                'updated_at' => '2019-03-05 18:50:50',
            ),
            110 => 
            array (
                'id' => 137,
                'locker_id' => 6,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/substation/04.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-03-05 18:50:57',
                'updated_at' => '2019-03-05 18:50:57',
            ),
            111 => 
            array (
                'id' => 138,
                'locker_id' => 6,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/substation/05.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-03-05 18:51:07',
                'updated_at' => '2019-03-05 18:51:07',
            ),
            112 => 
            array (
                'id' => 139,
                'locker_id' => 6,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/substation/06.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-03-05 18:51:15',
                'updated_at' => '2019-03-05 18:51:15',
            ),
            113 => 
            array (
                'id' => 140,
                'locker_id' => 2,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/svyaz/carousel_svyaz12_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:00:09',
                'updated_at' => '2019-02-14 15:00:09',
            ),
            114 => 
            array (
                'id' => 141,
                'locker_id' => 5,
                'type' => 1,
                'image_path' => '/storage/uploads/shkafy-individualnoi-sborki/nku/carousel_nku01_compressed.jpg',
                'alt_name' => NULL,
                'url' => NULL,
                'created_at' => '2019-02-14 15:32:35',
                'updated_at' => '2019-02-14 15:32:35',
            ),
        ));
        
        
    }
}